# Generated by Django 5.0.1 on 2024-01-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_userprofile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
