# Generated by Django 5.0.1 on 2024-01-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_alter_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='sender',
        ),
    ]
