# Generated by Django 5.0.1 on 2024-01-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
