# Generated by Django 5.0.1 on 2024-01-31 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_user_password_combinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_combinations',
        ),
    ]
