# Generated by Django 5.0.1 on 2024-01-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_user_password_combinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='combinations',
            field=models.JSONField(default=list),
        ),
    ]
